# KiBot configuration for JLCPCB manufacturing outputs
# Project: T-DSP TAC5212 Pro Audio Module
# Board: 4-layer (F.Cu, In1.Cu, In2.Cu, B.Cu)

kibot:
  version: 1

filters:
  - name: only_jlc_parts
    comment: 'Only parts with LCSC code'
    type: generic
    include_only:
      - column: 'LCSC'
        regex: '^C\d+'

variants:
  - name: rotated
    comment: 'JLCPCB rotation correction'
    type: kibom
    variant: rotated
    pre_transform: _rot_footprint_jlcpcb

outputs:
  - name: JLCPCB_gerbers
    comment: Gerbers compatible with JLCPCB
    type: gerber
    dir: t-dsp_tac5212_pro_audio_module
    options:
      exclude_edge_layer: true
      exclude_pads_from_silkscreen: true
      plot_sheet_reference: false
      plot_footprint_refs: true
      plot_footprint_values: false
      force_plot_invisible_refs_vals: false
      tent_vias: true
      use_protel_extensions: true
      create_gerber_job_file: false
      disable_aperture_macros: true
      gerber_precision: 4.6
      use_gerber_x2_attributes: false
      use_gerber_net_attributes: false
      line_width: 0.1
      subtract_mask_from_silk: true
      inner_extension_pattern: '.g%n'
    layers:
      - F.Cu
      - B.Cu
      - In1.Cu
      - In2.Cu
      - F.SilkS
      - B.SilkS
      - F.Mask
      - B.Mask
      - F.Paste
      - B.Paste
      - Edge.Cuts

  - name: JLCPCB_drill
    comment: Drill files compatible with JLCPCB
    type: excellon
    dir: t-dsp_tac5212_pro_audio_module
    options:
      pth_and_npth_single_file: false
      pth_id: '-PTH'
      npth_id: '-NPTH'
      metric_units: true
      map: gerber
      route_mode_for_oval_holes: false
      output: "%f%i.%x"

  - name: JLCPCB_position
    comment: Pick and place file, JLCPCB style
    type: position
    dir: t-dsp_tac5212_pro_audio_module
    options:
      variant: rotated
      output: '%f_cpl.%x'
      format: CSV
      units: millimeters
      separate_files_for_front_and_back: false
      only_smd: true
      columns:
        - id: Ref
          name: Designator
        - Val
        - Package
        - id: PosX
          name: "Mid X"
        - id: PosY
          name: "Mid Y"
        - id: Rot
          name: Rotation
        - id: Side
          name: Layer

  - name: JLCPCB_bom
    comment: BoM for JLCPCB
    type: bom
    dir: t-dsp_tac5212_pro_audio_module
    options:
      output: '%f_bom_JLCPCB.%x'
      exclude_filter: 'only_jlc_parts'
      ref_separator: ','
      columns:
        - field: Value
          name: Comment
        - field: References
          name: Designator
        - Footprint
        - field: 'LCSC'
          name: 'LCSC Part #'
      csv:
        hide_pcb_info: true
        hide_stats_info: true
        quote_all: true

  - name: generic_bom
    comment: Full BoM for general use (PCBWay, etc.)
    type: bom
    dir: t-dsp_tac5212_pro_audio_module
    options:
      output: '%f_bom_generic.%x'
      ref_separator: ','
      columns:
        - field: References
          name: Designator
        - field: Value
          name: Value
        - field: Footprint
          name: Footprint
        - field: Quantity Per PCB
          name: Qty
        - field: 'Package / Case'
          name: Package
        - field: 'LCSC'
          name: LCSC
        - field: 'LCSC_Manufacturer'
          name: Manufacturer
        - field: 'LCSC_MPN'
          name: MPN
        - field: 'Description'
          name: Description
      csv:
        hide_pcb_info: true
        hide_stats_info: true
        quote_all: true

  - name: interactive_bom
    comment: Interactive HTML BOM
    type: ibom
    dir: t-dsp_tac5212_pro_audio_module
    options:
      output: '%f_ibom.%x'

  - name: manufacturing_zip
    comment: ZIP file with all manufacturing files
    type: compress
    dir: t-dsp_tac5212_pro_audio_module
    options:
      files:
        - from_output: JLCPCB_gerbers
          dest: /
        - from_output: JLCPCB_drill
          dest: /
        - from_output: JLCPCB_position
          dest: /
        - from_output: JLCPCB_bom
          dest: /
        - from_output: generic_bom
          dest: /
        - from_output: interactive_bom
          dest: /
